### ISSUE TITLE
Typescript error "Property 'getChildContext' does not exist on type 'VirtualizedList<ItemT>'.ts(2339)"

### ISSUE THREAD

**Issue by tslater** [brmenchl/maintain-visible-content-position-flatlist-alternative#2]
First off, thank you for putting this reference together. I went to try out the MyFlatList component and am getting a typescript error on line 317:
```
Property 'getChildContext' does not exist on type 'VirtualizedList<ItemT>'.ts(2339)
```
I'm running React 16.11.0.  getChildContext is supposed to work for 16.x?
(https://reactjs.org/docs/legacy-context.html)

**Comment by brmenchl** [comment]
Ooh, yep. I added this file https://github.com/brmenchl/maintain-visible-content-position-flatlist-alternative/blob/master/customTypes/VirtualizedListTypes.d.ts to override React types to mirror the actual Interface for VirtualizedList

**Comment by brmenchl** [comment]
I just pushed a new branch: https://github.com/brmenchl/maintain-visible-content-position-flatlist-alternative/tree/v2

It contains some of the changes we made to this implementation, including handling our own scroll metrics, since we can just derive that data easily from scroll events.

Let me know if it works for you!
